USE [TAC_KANBAN]
GO

INSERT INTO [dbo].[MA_CUSTOMER]([CUSTOMER_NAME],[CUSTOMER_SHOT])
     VALUES('HONDA','HATC')
	 
INSERT INTO [dbo].[MA_CUSTOMER]([CUSTOMER_NAME],[CUSTOMER_SHOT])
     VALUES('TOYOTA','TMT')
GO

