USE [TAC_KANBAN]
GO

INSERT INTO [dbo].[MA_OPT_USER]([USER_NAME],[PASSWORD],[ROLE_ID],[USER_CODE],[IMAGE])
     VALUES('user_01','test@123',1,'00000001',null);

INSERT INTO [dbo].[MA_OPT_USER]([USER_NAME],[PASSWORD],[ROLE_ID],[USER_CODE],[IMAGE])
     VALUES('user_02','test@123',2,'00000002',null);
	 
GO

