USE [TAC_KANBAN]
GO

INSERT INTO [dbo].[MA_MODEL]([MODEL_NAME],[CUSTOMER_ID],[PREFIX])
     VALUES('CIVIC',1,'2HC')
	 
INSERT INTO [dbo].[MA_MODEL]([MODEL_NAME],[CUSTOMER_ID],[PREFIX])
     VALUES('CR-V',1,'2WS')
	 
INSERT INTO [dbo].[MA_MODEL]([MODEL_NAME],[CUSTOMER_ID],[PREFIX])
     VALUES('ACCORD',1,'2PX')
	 
INSERT INTO [dbo].[MA_MODEL]([MODEL_NAME],[CUSTOMER_ID],[PREFIX])
     VALUES('CITY',1,'2PK')
	 
INSERT INTO [dbo].[MA_MODEL]([MODEL_NAME],[CUSTOMER_ID],[PREFIX])
     VALUES('CITY',1,'2PU')
	 
INSERT INTO [dbo].[MA_MODEL]([MODEL_NAME],[CUSTOMER_ID],[PREFIX])
     VALUES('CITY',1,'2CT')
	 
INSERT INTO [dbo].[MA_MODEL]([MODEL_NAME],[CUSTOMER_ID],[PREFIX])
     VALUES('JAZZ',1,'2AP')
	 
INSERT INTO [dbo].[MA_MODEL]([MODEL_NAME],[CUSTOMER_ID],[PREFIX])
     VALUES('BRIO',1,'2CV')
	 
INSERT INTO [dbo].[MA_MODEL]([MODEL_NAME],[CUSTOMER_ID],[PREFIX])
     VALUES('AMAZE-SD',1,'2TP')
	 
INSERT INTO [dbo].[MA_MODEL]([MODEL_NAME],[CUSTOMER_ID],[PREFIX])
     VALUES('ACCORD',1,'2PT')
	  
INSERT INTO [dbo].[MA_MODEL]([MODEL_NAME],[CUSTOMER_ID],[PREFIX])
     VALUES('ACCORD',1,'2GA')
	 
INSERT INTO [dbo].[MA_MODEL]([MODEL_NAME],[CUSTOMER_ID],[PREFIX])
     VALUES('SOLUNA',1,'482L')
	 
GO

