USE [TAC_KANBAN]
GO

INSERT INTO [dbo].[MA_LINE]([LINE_NAME],[FACTORY_ID])
     VALUES('EXT_01',1)
	 
INSERT INTO [dbo].[MA_LINE]([LINE_NAME],[FACTORY_ID])
     VALUES('EXT_02',1)
	 
INSERT INTO [dbo].[MA_LINE]([LINE_NAME],[FACTORY_ID])
     VALUES('EXT_03',1)

INSERT INTO [dbo].[MA_LINE]([LINE_NAME],[FACTORY_ID])
     VALUES('EXT_04',2)

INSERT INTO [dbo].[MA_LINE]([LINE_NAME],[FACTORY_ID])
     VALUES('EXT_05',2)
	 
INSERT INTO [dbo].[MA_LINE]([LINE_NAME],[FACTORY_ID])
     VALUES('EXT_06',2)
GO

